apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  config.index.js: |
    // 启用cloud配置文件
    module.exports = require('./config.cloud');

  config.cloud.js: |
    module.exports = {
        // 固定配置
        isRemoteConfig: true,
        isHTTPS: false,
        APP_PORT: {{ .Values.service.targetPort }},
        isSOCKET: false,
        APP_COOKIE: "nodeManageToken",
        NACOS_IP: "nacos-headless.iottepa:8848",
        NACOS_NAME_SPACE: "public",
        NACOS_SERVICE_NAME: "fzgang-node-manage",
        NACOS_GROUP_NAME: "DEFAULT_GROUP",
        NACOS_CONFIG: "all-base-service-config-cloud.json",
        JWT_TOKEN: "manageStoreToken",
        JWT_IP_TIME: 300,
        HTTPS_KEY: "/ssl/https/webserver.key",	//https证书秘钥
        HTTPS_CERT: "/ssl/https/webserver.crt",	//https证书
        // 如果启用本地配置
        DB_HOST: "{{ .Values.app.DB_HOST }}",
        DB_NAME: "{{ .Values.app.DB_NAME }}",
        DB_PORT: "{{ .Values.app.DB_PORT }}",
        DB_USER: "{{ .Values.app.DB_USER }}",
        DB_PASSWORD: "{{ .Values.app.DB_PASSWORD }}",
        DB_UNSECURE: {{ .Values.app.DB_UNSECURE }},
        RABBITMQ_HOSTNAME: "{{ .Values.app.RABBITMQ_HOSTNAME }}",
        RABBITMQ_PORT: {{ .Values.app.RABBITMQ_PORT }},
        RABBITMQ_USERNAME: "{{ .Values.app.RABBITMQ_USERNAME }}",
        RABBITMQ_PASSWORD: "{{ .Values.app.RABBITMQ_PASSWORD }}",
        RABBITMQ_PROTOCOL: "{{ .Values.app.RABBITMQ_PROTOCOL }}",
        RABBITMQ_LOCALE: "{{ .Values.app.RABBITMQ_LOCALE }}",
        RABBITMQ_FRAMEMAX: {{ .Values.app.RABBITMQ_FRAMEMAX }},
        RABBITMQ_HEARTBEAT: {{ .Values.app.RABBITMQ_HEARTBEAT }},
        RABBITMQ_VHOST: "{{ .Values.app.RABBITMQ_VHOST }}",
        RABBITMQ_SSl: {{ .Values.app.RABBITMQ_SSl }},
        RABBITMQ_CERTFILEPATH: "{{ .Values.app.RABBITMQ_CERTFILEPATH }}",
        RABBITMQ_KEYFILEPATH: "{{ .Values.app.RABBITMQ_KEYFILEPATH }}",
        RABBITMQ_PASSPHRASE: "{{ .Values.app.RABBITMQ_PASSPHRASE }}",
        RABBITMQ_CAFILEPATH: "{{ .Values.app.RABBITMQ_CAFILEPATH }}",
        RD_FAMILY: {{ .Values.app.RD_FAMILY }},
        RD_PASSWORD: "",
        RD_DB: {{ .Values.app.RD_DB }},
        PREFIX_IP_ADDRESS: "10.", // ip前缀
        RD_NAME: "{{ .Values.app.RD_NAME }}",
        REDIS_MEMBERS: [{"port":6379, "host":"redis-master.iottepa"}],
        // 三种接入模式 standalone(单机模式) sentinel(哨兵模式) cluster(集群模式)，默认是standalone
        REDIS_TEYP: "{{ .Values.app.REDIS_TEYP }}",
        // 持久化开始标识符（勿删）
        /**everlasting-start**/
        /**everlasting-end**/
    };
