apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }} # 副本数量
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      # imagePullSecrets:
      #   - name: docker-registry-secret
      containers:
        - name: {{ .Values.deployment.name }}
          image: '{{ .Values.deployment.image }}:{{ .Values.deployment.imageTag }}' # 镜像版本
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }} # POD端口
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            limits:
              memory: 2500Mi
            requests:
              memory: 500Mi
          volumeMounts:
            - name: config-index-js
              mountPath: /opt/node_app/config/index.js
              subPath: index.js
            - name: config-cloud-js
              mountPath: /opt/node_app/config/config.cloud.js
              subPath: config.cloud.js
            - name: rabbitmq
              mountPath: /ssl/rabbitmq
              readOnly: true
            - name: download
              mountPath: /mnt/download
      volumes:
        - name: config-index-js
          configMap:
            name: {{ .Values.configMap.name }}
            items:
              - key: config.index.js
                path: index.js
        - name: config-cloud-js
          configMap:
            name: {{ .Values.configMap.name }}
            items:
              - key: config.cloud.js
                path: config.cloud.js
        - name: rabbitmq
          persistentVolumeClaim:
            claimName: {{ .Values.deployment.existingPersistentVolumeClaim.rabbitmq }}
        - name: download
          hostPath:
            path: /mnt/download
            type: Directory
      initContainers:
        - name: volume-permissions
          image: docker.io/bitnami/bitnami-shell:10-debian-10-r265
          command: ['sh', '-c', 'chown -R 999:999 /ssl/rabbitmq']
          volumeMounts:
          - name: rabbitmq
            mountPath: /ssl/rabbitmq
        - name: init-operation-center
          image: k8s-wait-for-endpoint:1.0.0
          args: ['--name=operation-center', '--namespace={{ .Release.Namespace }}']
