deployment:
  name: nodejs-manage # 部署名
  image: docker.iottepa.cn:32011/uecm-nodejs-manage # 镜像版本
  imageTag: 6.1.1-rc39
  imagePullPolicy: IfNotPresent # 镜像拉取策略
  replicas: 1 # 副本数量
  existingPersistentVolumeClaim: 
    file: uecm-nodejs
    rabbitmq: uecm-rabbitmq-certificate

app:
  DB_HOST: mysql-headless.iottepa
  DB_NAME: Galaxy
  DB_PORT: 3306
  DB_USER: root
  DB_PASSWORD: 123456
  DB_UNSECURE: true
  RD_FAMILY: 4
  RD_DB: 0
  RD_NAME: wanwoomaster
  # 三种接入模式 standalone(单机模式) sentinel(哨兵模式) cluster(集群模式)，默认是standalone
  REDIS_TEYP: standalone
  REDIS_MEMBERS: "[{port:6379, host:'redis-master.iottepa'}]"
  RABBITMQ_HOSTNAME: rabbitmq-headless.iottepa
  RABBITMQ_PORT: 5671
  RABBITMQ_USERNAME: admin
  RABBITMQ_PASSWORD: Wanwoo@123
  RABBITMQ_PROTOCOL: amqps
  RABBITMQ_LOCALE: zh-CN
  RABBITMQ_FRAMEMAX: 0
  RABBITMQ_HEARTBEAT: 0
  RABBITMQ_VHOST: /
  RABBITMQ_SSl: true
  RABBITMQ_CERTFILEPATH: /ssl/rabbitmq/server_certificate.pem
  RABBITMQ_KEYFILEPATH: /ssl/rabbitmq/server_key.pem
  RABBITMQ_PASSPHRASE: Wanwoo@123
  RABBITMQ_CAFILEPATH: /ssl/rabbitmq/ca_certificate.pem

configMap:
  name: nodejs-manage # 配置名

minio:
  path: http://k8s-oss-minio.default:9000
  rootPassword: Wanwoo@123
  rootUser: admin


service:
  name: nodejs-manage # Service服务名
  ##
  # 服务类型（网络类型），可选值如下
  # LoadBalancer 负载均衡，集群外可访问
  # ClusterIP 仅限集群内部访问
  ##
  type: ClusterIP # Service网络类型
  port: 80 # Service服务端口
  targetPort: 18701 # POD端口

